[0m12:58:08.424586 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B1C7D47F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B1F113580>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B1F1133A0>]}


============================== 12:58:08.424586 | 069c8b2e-3dfa-4507-acc4-5964dac36cca ==============================
[0m12:58:08.424586 [info ] [MainThread]: Running with dbt=1.8.3
[0m12:58:08.424586 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Gurdit Singh\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt seed', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:58:08.424586 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path E:\Projects\LearnDuckdb\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:58:08.444074 [debug] [MainThread]: Command `dbt seed` failed at 12:58:08.443070 after 0.17 seconds
[0m12:58:08.446104 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B1C7D47F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B1F113520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024B1F113610>]}
[0m12:58:08.447616 [debug] [MainThread]: Flushing usage events
[0m22:40:17.963976 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019532E447F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019535773580>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000195357733A0>]}


============================== 22:40:18.017431 | a85be2d3-a9ab-4a76-bfc4-ac8cb4d27c52 ==============================
[0m22:40:18.017431 [info ] [MainThread]: Running with dbt=1.8.3
[0m22:40:18.017431 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\Gurdit Singh\\.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt seed', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m22:40:18.017431 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path E:\Projects\LearnDuckdb\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:40:18.030705 [debug] [MainThread]: Command `dbt seed` failed at 22:40:18.029606 after 0.23 seconds
[0m22:40:18.035232 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019532E447F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019535773520>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000019535773610>]}
[0m22:40:18.054109 [debug] [MainThread]: Flushing usage events
